version: '3.8'

services:

  app:
    image: nextjs-jwt-auth-app:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Load environment variables from .env file (NOT copied into image)
    env_file:
      - .env
    environment:
      # Override specific variables if needed
      DATABASE_URL: "mongodb+srv://akash:DVJ4k8fSb0qey3oe@akash-play.zay1bq8.mongodb.net/devops-assignment"
      NODE_ENV: production
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

