version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/nextjs-auth?replicaSet=rs0
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NEXTAUTH_SECRET=your-nextauth-secret-change-this-in-production
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=nextjs-auth
    command: mongod --replSet rs0
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
