apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: da
type: Opaque
stringData:
  database-url: "mongodb+srv://akash:DVJ4k8fSb0qey3oe@akash-play.zay1bq8.mongodb.net/devops-assignment"
  jwt-secret: "abcdefgh"
  nextauth-secret: "abcdefgh"
